name:                cica
version:             0.1.0.0
github:              "via119/cica"
license:             BSD3
author:              "via"
maintainer:          "budavolgyi.vivien@gmail.com"
copyright:           "value"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            value

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/via119/cica#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  cica-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cica
    - network
    - stm

tests:
  cica-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cica
